# classification/config.yaml
experiment_name: BaseHistologyClassifier_Histology_ADAM_Batch128

# Model configuration
model:
  architecture: BaseHistologyClassifier # Specify the desired model architecture
  num_classes: 4

training:
  batch_size: 128
  epochs: 100

optimizer_config:
  learning_rate: 1e-4
  type: Adam
  betas: [0.9, 0.999]

# Evaluation configuration
validation:
  batch_size: 64

# Data configuration
data:
  name: Histology_Dataset
  data_dir:
    train_data_path: data/Histology_Dataset/
    val_data_path: data/Histology_Dataset/
    test_data_path: data/Histology_Dataset/
  num_classes: 4
  split_ratio:
    train_test: 0.1 # 80% for training and 10% for testing
    train_val: 0.1 # 90% for training and 10% for validation
  transform:
    normalization_params:
      train:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      test:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    RandomResizedCrop: [32,32]
    RandomHorizontalFlip: true
  random_seed: 32


